##### Greetings ########################################################################################################
# Comment to be posted to welcome users when they open their first PR
firstPRWelcomeComment: >
  Hi there :wave: Congratulations on sending your first PR here :sparkles: Your PR will be reviewed soon, in the meantime it would be great if you could star :star: this repo :smiley:

